
[global]
    TopFolder = "C:/MAST"

[server]
    host = "0.0.0.0"            # listen on all interfaces
    port = 8000

[stages.controller]
    ipaddr = "169.254.98.7"     # IP address of the controller
    port = 55550

[stages.grating]
    axis_id = 1
    # startup = ...
    # shutdown = ...
    presets = { Ca = 1000, Halpha  = 2000, Mg = 3000 }

[stages.camera]
    axis_id = 2
    presets = { Ca = 10000, Halpha = 15000, Mg = 20000 }

[stages.fiber]
    axis_id = 3
    presets = { DeepSpec = 1000, HighSpec = 2000 }

[filter-wheel.1]
    serial_number = "TP03242738-30033"
    Pos1 = "Empty"
    Pos2 = "ND1000"
    Pos3 = "ND2000"
    Pos4 = "ND3000"
    Pos5 = "ND4000"
    Pos6 = "ND5000"
    Default = "Pos1"

[filter-wheel.2]
    serial_number = "TP03242738-30034"
    Pos1 = "Empty"
    Pos2 = "ND1000"
    Pos3 = "ND2000"
    Pos4 = "ND3000"
    Pos5 = "ND4000"
    Pos6 = "ND5000"
    Default = "Pos1"
